### ISSUE TITLE
Reduce requests to server

### ISSUE THREAD

**Issue by rajatjain1997** [rajatjain1997/Content-Rectifier-II#6]
The current number of requests to server are too high. Use socket.io to contain calls. Try storing the data locally and send it to server at a specified interval.

Also, the server must be able to send messages to the bot for any developments.

**Comment by rajatjain1997** [comment]
Bot issue resolved.

**Comment by Us3rRogu3** [comment]
Solved in Commit 58c108039a00c52a608a50a7e5a2d36cf11cb595
