### ISSUE TITLE
Extension can be deactivated without consent from parent

### ISSUE THREAD

**Issue by rajatjain1997** [rajatjain1997/Content-Rectifier-II#8]
Currently Google Chrome and other browser platforms do not allow blocking of extension defaults. We need to at-least send a message to the parent about this, and only allow deactivation if permissions are provided.

**Comment by rajatjain1997** [comment]
This URL can be used to send a message to the server that the extension is being uninstalled-> https://developer.chrome.com/extensions/runtime#method-setUninstallURL

We can then forward a message to the parent regarding the same.

Also, disabling/uninstalling the extension will cause the corresponding socket to disconnect and emit a message to the server. The same event can be used to identify the user and forward a message about the same.

**Comment by rajatjain1997** [comment]
Uninstall URL set in b4f9172fcf0c19b8e8cc6398ff307bc9cd1d80b3.

**Comment by Mrigesh08** [comment]
partially addressed this issue in 115e6b2. We now just need to communicate between the 2 extensions and send email and childname to the other extension.

**Comment by rajatjain1997** [comment]
Solved in 013b3c91db35c3f242799b7dd8d69e037b4b8cac
